input_file: data/ftrs_test_data.ftrs
# input_file: data/maxquant_test_data.txt
masses_file: data/masses/e_coli_monomer_masses.csv
ppm_tolerance: 10
time_delta: 0.5
mod_list:
  - none # All modifications disabled, comment this line and uncomment the following modifications you wish to use.
#  - Sodium
#  - Potassium
#  - Anhydro
#  - DeAc
#  - Deacetyl_Anhydro
#  - Nude
#  - Decay
#  - Amidation
#  - Amidase
#  - Double_Anh
#  - Multimers
#  - multimers_Glyco
#  - Multimers_Lac
#  - O-Acetylated
output_dir: output
warnings: ignore
quiet: false
float_format: 4
